### ISSUE TITLE
Code Formatter Specification

### ISSUE THREAD

**Issue by hesic73** [markusgrotz/peract_bimanual#11]
I'm Sicheng, and I'm working on incorporating our method into the codebase. However, I've noticed that the code formatting in my environment (using autopep8) differs from the formatting in the existing codebase. Could you please provide the standard code formatter or any specific configuration that should be followed to maintain consistency?

Thank you for your assistance.

**Comment by markusgrotz** [comment]
Thank you Sicheng! I am using black as code formatter. I added a comment in the README.md and formatted missing code. 

I hope this helps. Let me know if you have any further questions.
