### ISSUE TITLE
Question about the depth in dataset

### ISSUE THREAD

**Issue by HealorCai** [markusgrotz/peract_bimanual#13]
Hello there,

I hope this message finds you well. I'm reaching out to discuss an issue we've encountered while working with your provided dataset. We've noticed that there appears to be a discrepancy in the depth information stored as PNG files.

Upon closer examination, we found that the depth values were encoded into the RGB channels with different operations for each channel:

The red channel (high byte) was calculated using division by 256.
The green channel (middle byte) was calculated using modulo 255 after division by 256.
The blue channel (low byte) was calculated using modulo 255 directly on the depth value.
This inconsistency makes it challenging for us to accurately reconstruct the depth information from the dataset. The non-uniform division and modulo operations lead to a loss of precision and potential data corruption when attempting to decode the depth values back from the RGB channels.

Red channel: r = (f / 256) / 256
Green channel: g = (f / 256) % 255
Blue channel: b = f % 255

We kindly request that you consider updating the dataset to ensure that the depth information is consistently and accurately encoded across all RGB channels. This would greatly improve the dataset's usability and allow for reliable reconstruction of depth data.

Thank you for your attention to this matter, and we look forward to your response.

Best regards

**Comment by markusgrotz** [comment]
Thank you, I fixed the code, updated the dataset and run some training with an image resolution 128x128. I also renamed some of the tasks, added additional data as well as a script to visualize an episode. I am currently running more tests and will update the webpage soon. Training longer seems to help more :)
