### ISSUE TITLE
Hello, I also encountered the same problem when downloading the dataset. Can you provide another way to download the dataset?

### ISSUE THREAD

**Issue by hi-yuanxu** [markusgrotz/peract_bimanual#14]

**Comment by markusgrotz** [comment]
Thank you for your interest. Unfortunately, I run out of disk space and I am working on a solution. I removed the 128x128 dataset. Meanwhile, you can find the large image size here:

https://dataset.cs.washington.edu/fox/bimanual/image_size_256/

Please note that the bimanual_take_tray_out_of_oven is unavailable. I am uploading them to a temporary location. Once they will be available you can download them here

```

curl -4 ftp://ftp.cs.washington.edu/outgoing/peract_bimanual/bimanual_take_tray_out_of_oven.test.squashfs -o bimanual_take_tray_out_of_oven.test.squashfs
curl -4 ftp://ftp.cs.washington.edu/outgoing/peract_bimanual/bimanual_take_tray_out_of_oven.train.squashfs -o bimanual_take_tray_out_of_oven.train.squashfs
curl -4 ftp://ftp.cs.washington.edu/outgoing/peract_bimanual/bimanual_take_tray_out_of_oven.val.squashfs -o bimanual_take_tray_out_of_oven.val.squashfs
```

**Comment by hi-yuanxu** [comment]
Thank you. But it seems that the file "bimanual_pick_plate.test.squashfs" is missing.

**Comment by markusgrotz** [comment]
I repacked the dataset and requested a quota increase for file storage. I am currently uploading it. It takes a while as I am traveling. I will let you know when I am done.

**Comment by markusgrotz** [comment]
Should be downloadable from the website now. Let me know if you have any issues.
