### ISSUE TITLE
what is the action in the datasets?

### ISSUE THREAD

**Issue by pxlong** [markusgrotz/peract_bimanual#16]
Hi, thanks for open-sourcing this great work.

I am just wondering what is the action (defined by end-effector pose? or waypoints? or joint positions?) in the dataset?  
Many thanks

**Comment by markusgrotz** [comment]
Hi Pinxin,

Thank you very much for your interest. The action is the end-effector pose and stored as (translation, quaternion) as well as matrix. Additionally, joint positions and joint velocities are also saved.

Does this help you? Happy to chat about this.

Kind regards,
Markus

**Comment by pxlong** [comment]
Hi Markus, 

Many thanks for your reply. 

I see. Actions are also saved in low_dim_obs.pkl just like other low dim states of the robot.
