### ISSUE TITLE
Training cost

### ISSUE THREAD

**Issue by aopolin-lv** [markusgrotz/peract_bimanual#3]
Hi, authors.PerAct2 is a wonderful study which brings our attention to the bimanual tasks. I wonder that how it cost when training the agent. For example, 8*v100-16g 16 days like peract?

**Comment by markusgrotz** [comment]
Hi @aopolin-lv,

Thank you very much for your interest in our work. Can you clarify if you are looking for multi-task training?

**Comment by aopolin-lv** [comment]
Yes! You are right. In my case, I want to train a multi-task policy. Additionally, I reviewed the paper, and the results in Table 3 were all obtained through single-task training, right? According to Table 4, the training time for multi-task learning is very high and the performance is quite poor. Do you have any good suggestions for multi-task learning?
