### ISSUE TITLE
Could you provide another way to download datasett?

### ISSUE THREAD

**Issue by aopolin-lv** [markusgrotz/peract_bimanual#4]
Hello, authors. I tried many times to download datasets but failed. Could you provide another way to download dataset, such as Google driver?

**Comment by markusgrotz** [comment]
Hi @aopolin-lv,

I'm sorry to hear that you're having trouble downloading the dataset. Unfortunately, I haven't really found a good long-term hosting option yet as the data is quite larger. Can you send me an e-mail so I can provide you with an alternative download option?

Kind regards,
Markus

**Comment by aopolin-lv** [comment]
Thank you. I have sent e-mail. Waiting for the response.

**Comment by markusgrotz** [comment]
Hi Qi, I just send you a link with the files to the tasks you mentioned. I hope this helps.

**Comment by aopolin-lv** [comment]
There is still a problem with the ftp server and files cannot be obtained.

**Comment by aopolin-lv** [comment]
> Hi Qi, I just send you a link with the files to the tasks you mentioned. I hope this helps.

There is still a problem with the ftp server and files cannot be obtained.

**Comment by markusgrotz** [comment]
Uploaded the files again, as files are removed after a couple of days.

**Comment by aopolin-lv** [comment]
> Uploaded the files again, as files are removed after a couple of days.

Thanks. I see the files again and continue to download them.

**Comment by aopolin-lv** [comment]
> Hello, I also encountered the same problem when downloading the dataset. Can you provide another way to download the dataset?

Sorry, the author gave me a link address, which is currently invalid. If needed, contact the author
