### ISSUE TITLE
Inquiry About the Release Status of Extended RLBench Simulation Platform

### ISSUE THREAD

**Issue by HealorCai** [markusgrotz/peract_bimanual#5]
Dear authors, thank you for your outstanding work on the PerAct^2 project.

 I noticed the availability of the demonstration dataset, but I am unsure whether the extended RLBench simulation platform you used in your research has also been released. I would like to inquire if the platform is currently available, or if there are any plans for its release in the near future.

**Comment by markusgrotz** [comment]
Hi,

Thank you for your interested in our work. Yes, I also released the modifications. The link is hidden in the installation instructions. The RLBench fork with the modifications is here: https://github.com/markusgrotz/RLBench

Let me know if this works for you!

**Comment by HealorCai** [comment]
Thank you for the link! I’ll try it out and let you know if I have any questions.

Best regards！

**Comment by markusgrotz** [comment]
You are welcome!
